esphome:

esp32:
  board: esp32-p4-evboard
  cpu_frequency: 400MHz
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes

external_components:    
  - source: github://kvj/esphome@jd9365_gsl3680
    refresh: 0s
    components: [gsl3680]

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

ota:
  platform: esphome

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

button:
  - platform: restart
    name: "Reboot"

esp_ldo:
  - channel: 3
    voltage: 2.5V

switch:
  - id: backlight_
    platform: gpio
    pin: GPIO23
    restore_mode: ALWAYS_ON
    name: Backlight
    entity_category: config
    icon: "mdi:brightness-6"

psram:
  speed: 200MHz

display:
  - platform: mipi_dsi
    model: CUSTOM
    dimensions:
      height: 1280
      width: 800
    hsync_pulse_width: 20
    hsync_back_porch: 20
    hsync_front_porch: 40
    vsync_pulse_width: 4
    vsync_back_porch: 8
    vsync_front_porch: 20 
    lane_bit_rate: 1000Mbps
    pclk_frequency: 60Mhz
    color_order: rgb
    pixel_mode: 16bit
    color_depth: 16
    byte_order: little_endian
    rotation: 0
    reset_pin: 27
    draw_rounding: 4
    init_sequence:
     - [0xE0,0x00]
     - [0xE1,0x93]
     - [0xE2,0x65]
     - [0xE3,0xF8]
     - [0x80,0x01]
     - [0xE0,0x01]
     - [0x00,0x00]
     - [0x01,0x39]
     - [0x03,0x10]
     - [0x04,0x41]
     - [0x0C,0x74]
     - [0x17,0x00]
     - [0x18,0xD7]
     - [0x19,0x00]
     - [0x1A,0x00]
     - [0x1B,0xD7]
     - [0x1C,0x00]
     - [0x24,0xFE]
     - [0x35,0x26]
     - [0x37,0x69]
     - [0x38,0x05]
     - [0x39,0x06]
     - [0x3A,0x08]
     - [0x3C,0x78]
     - [0x3D,0xFF]
     - [0x3E,0xFF]
     - [0x3F,0xFF]
     - [0x40,0x06]
     - [0x41,0xA0]
     - [0x43,0x14]
     - [0x44,0x0B]
     - [0x45,0x30]
     - [0x4B,0x04]
     - [0x55,0x02]
     - [0x57,0x89]
     - [0x59,0x0A]
     - [0x5A,0x28]
     - [0x5B,0x15]
     - [0x5D,0x50]
     - [0x5E,0x37]
     - [0x5F,0x29]
     - [0x60,0x1E]
     - [0x61,0x1D]
     - [0x62,0x12]
     - [0x63,0x1A]
     - [0x64,0x08]
     - [0x65,0x25]
     - [0x66,0x26]
     - [0x67,0x28]
     - [0x68,0x49]
     - [0x69,0x3A]
     - [0x6A,0x43]
     - [0x6B,0x3A]
     - [0x6C,0x3B]
     - [0x6D,0x32]
     - [0x6E,0x1F]
     - [0x6F,0x0E]
     - [0x70,0x50]
     - [0x71,0x37]
     - [0x72,0x29]
     - [0x73,0x1E]
     - [0x74,0x1D]
     - [0x75,0x12]
     - [0x76,0x1A]
     - [0x77,0x08]
     - [0x78,0x25]
     - [0x79,0x26]
     - [0x7A,0x28]
     - [0x7B,0x49]
     - [0x7C,0x3A]
     - [0x7D,0x43]
     - [0x7E,0x3A]
     - [0x7F,0x3B]
     - [0x80,0x32]
     - [0x81,0x1F]
     - [0x82,0x0E]
     - [0xE0,0x02]
     - [0x00,0x1F]
     - [0x01,0x1F]
     - [0x02,0x52]
     - [0x03,0x51]
     - [0x04,0x50]
     - [0x05,0x4B]
     - [0x06,0x4A]
     - [0x07,0x49]
     - [0x08,0x48]
     - [0x09,0x47]
     - [0x0A,0x46]
     - [0x0B,0x45]
     - [0x0C,0x44]
     - [0x0D,0x40]
     - [0x0E,0x41]
     - [0x0F,0x1F]
     - [0x10,0x1F]
     - [0x11,0x1F]
     - [0x12,0x1F]
     - [0x13,0x1F]
     - [0x14,0x1F]
     - [0x15,0x1F]
     - [0x16,0x1F]
     - [0x17,0x1F]
     - [0x18,0x52]
     - [0x19,0x51]
     - [0x1A,0x50]
     - [0x1B,0x4B]
     - [0x1C,0x4A]
     - [0x1D,0x49]
     - [0x1E,0x48]
     - [0x1F,0x47]
     - [0x20,0x46]
     - [0x21,0x45]
     - [0x22,0x44]
     - [0x23,0x40]
     - [0x24,0x41]
     - [0x25,0x1F]
     - [0x26,0x1F]
     - [0x27,0x1F]
     - [0x28,0x1F]
     - [0x29,0x1F]
     - [0x2A,0x1F]
     - [0x2B,0x1F]
     - [0x2C,0x1F]
     - [0x2D,0x1F]
     - [0x2E,0x52]
     - [0x2F,0x40]
     - [0x30,0x41]
     - [0x31,0x48]
     - [0x32,0x49]
     - [0x33,0x4A]
     - [0x34,0x4B]
     - [0x35,0x44]
     - [0x36,0x45]
     - [0x37,0x46]
     - [0x38,0x47]
     - [0x39,0x51]
     - [0x3A,0x50]
     - [0x3B,0x1F]
     - [0x3C,0x1F]
     - [0x3D,0x1F]
     - [0x3E,0x1F]
     - [0x3F,0x1F]
     - [0x40,0x1F]
     - [0x41,0x1F]
     - [0x42,0x1F]
     - [0x43,0x1F]
     - [0x44,0x52]
     - [0x45,0x40]
     - [0x46,0x41]
     - [0x47,0x48]
     - [0x48,0x49]
     - [0x49,0x4A]
     - [0x4A,0x4B]
     - [0x4B,0x44]
     - [0x4C,0x45]
     - [0x4D,0x46]
     - [0x4E,0x47]
     - [0x4F,0x51]
     - [0x50,0x50]
     - [0x51,0x1F]
     - [0x52,0x1F]
     - [0x53,0x1F]
     - [0x54,0x1F]
     - [0x55,0x1F]
     - [0x56,0x1F]
     - [0x57,0x1F]
     - [0x58,0x40]
     - [0x59,0x00]
     - [0x5A,0x00]
     - [0x5B,0x10]
     - [0x5C,0x05]
     - [0x5D,0x50]
     - [0x5E,0x01]
     - [0x5F,0x02]
     - [0x60,0x50]
     - [0x61,0x06]
     - [0x62,0x04]
     - [0x63,0x03]
     - [0x64,0x64]
     - [0x65,0x65]
     - [0x66,0x0B]
     - [0x67,0x73]
     - [0x68,0x07]
     - [0x69,0x06]
     - [0x6A,0x64]
     - [0x6B,0x08]
     - [0x6C,0x00]
     - [0x6D,0x32]
     - [0x6E,0x08]
     - [0xE0,0x04]
     - [0x2C,0x6B]
     - [0x35,0x08]
     - [0x37,0x00]
     - [0xE0,0x00]
     - [0x11,0x00]
     - [0x29,0x00]
     - delay 5ms
     - [0x11,0x00]
     - delay 120ms
     - [0x35,0x00]

# i2c:
#   sda: GPIO7
#   scl: GPIO8
#   scan: true
#   frequency: 400kHz

output:
  - platform: template
    id: fake_output_
    type: float
    write_action: []

rtttl:
  - id: rtttl_
    output: fake_output_

# touchscreen:
#   - platform: gsl3680
#     id: touchscreen_
#     reset_pin: GPIO22
#     interrupt_pin: GPIO21
#     transform:
#       swap_xy: true
#       mirror_y: true
