esphome:
  name: lvgl-dashboard-indicators
  friendly_name: LVGL Desktop Indicators

external_components:
  - source: components
  - source: github://kvj/esphome@sdl_nice_window
    refresh: 30s
    components:
      - sdl

host:

logger:
  level: INFO

touchscreen:
  platform: sdl
  id: touchscreen_

display:
  - platform: sdl
    auto_clear_enabled: false
    update_interval: never
    window_options:
      resizable: false
      always_on_top: true
    allow_screensaver: true
    title: Home Assistant
    dimensions:
      width: 240
      height: 200

time:
  - platform: host
    timezone: Europe/Berlin

packages:
  common: !include {file: _dashboard.yaml, vars: {api_port: 6054, endian: big_endian}}

output:
  - platform: template
    id: fake_output_
    type: float
    write_action: []

rtttl:
  - id: rtttl_
    output: fake_output_

switch:
  - platform: template
    optimistic: true
    id: backlight_
    restore_mode: ALWAYS_ON
    name: Backlight
    internal: true

lvgl_dashboard:
  id: dashboard_
  mdi_font_small: mdi_30
  mdi_font_large: mdi_60
  normal_font: main_font_
  large_font: large_font_
  small_font: small_font_
  width: 180
  height: 180
  vertical: false
  backlight: backlight_
  switches: []
